name: Test
on: [push]
jobs:
  verify:
    name: Code verification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
      - name: Verify code (Black & iSort)
        run: |
          make check
      - name: Verify code (MyPy)
        run: |
          make mypy
      - name: Lint with flake8
        run: |
          make lint
  tests:
    name: Tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10', '3.11',]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: Test (pytest)
        run: |
          make test
  build:
    name: Build
    needs: [verify, tests]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10', '3.11']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build package
      run: |
        pip install setuptools wheel twine && python setup.py sdist
    - name: Install on the system
      run: |
        pip install dist/pip2spack* --force && pip2spack version
    - name: Test "create"
      run: | 
        mkdir spack_root_dir/var/spack/repos/builtin/packages
        export SPACK_ROOT=${PWD}/spack_root_dir
        pip2spack create scapy
    - name: Verify test "create"
      if: ${{ ls spack_root_d/var/spack/repos/builtin/packages/py-scapy/ -1 | wc -l }} != {{ 1 }}
      run: |
        exit 1